[package]
name = "tl-qa"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quick-xml.workspace = true
regex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip.workspace = true
tl-domain = { path = "../tl-domain" }
tl-filter-office = { path = "../tl-filter-office" }
