[package]
name = "tl-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ferrous-opencc.workspace = true
regex.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
tl-domain = { path = "../tl-domain" }
