[package]
name = "translunar-filter-interop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
translunar-domain = { path = "../domain" }
translunar-filter-core = { path = "../filter-core" }
translunar-filter-office-core = { path = "../filter-office-core" }
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
