[package]
name = "tl-filter-html"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quick-xml.workspace = true
thiserror.workspace = true
tl-domain = { path = "../tl-domain" }
tl-filter-core = { path = "../tl-filter-core" }
tl-segmentation = { path = "../tl-segmentation" }

[dev-dependencies]
tempfile.workspace = true
